# Generated by Django 3.0.5 on 2020-06-20 14:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('video', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=10)),
                ('categorias', models.CharField(choices=[('programacao', 'Programação'), ('python', 'Python'), ('django', 'Django')], default='programacao', max_length=12)),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 20, 11, 41, 23, 81283))),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('ativado', models.BooleanField(blank=True, default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('ativado', models.BooleanField(default=False)),
                ('data_publicacao', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 20, 11, 41, 23, 81283))),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=2)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Post')),
            ],
        ),
    ]
