# Generated by Django 3.0.5 on 2020-06-26 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200620_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 18, 30, 22, 559254)),
        ),
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 26, 18, 30, 22, 557256)),
        ),
    ]
